name: Puzzling PR Builder
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      #      - name: Create Local Properties
      #        run: touch local.properties
      #
      #      - name: Access Local Properties
      #        env:
      #          base_url: ${{ secrets.base_url }}
      #        run: |
      #          echo base_url=\"$base_url\" >> local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew buildeRelease

      slackNotify:
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        runs-on: ubuntu-latest
        steps:
          - name: Notify message to slack
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
              SLACK_COLOR: ${{ job.status }} # 또는 'green', '#ff00ff' 처럼 직접 색상 지정
              SLACK_USERNAME: PUZZLING AOS
              SLACK_TITLE: FAILED 🥲
              SLACK_MESSAGE: 'PR Check Failed ❌❌'